// Private Foundation Scholarships scraper

import { ScrapedScholarship, ScraperResult } from "../types";
import { normalizeScholarship } from "../utils/normalizer";
import { logger } from "../utils/logger";

const SOURCE = "PRIVATE";

const PRIVATE_SCHOLARSHIPS: Partial<ScrapedScholarship>[] = [
    {
        name: "Vidyadhan Scholarship Program",
        provider: "Sarojini Damodaran Foundation (Private)",
        description: "Private foundation scholarship aiming to support the college education of meritorious students from economically challenged families.",
        eligibility_criteria: "Students completing 10th grade. Minimum 90% or 9 CGPA in 10th. Available in selected states.",
        education_level: ["12th"],
        category: ["General", "OBC", "SC", "ST"],
        income_limit: 200000,
        marks_requirement: 90,
        state: "All India",
        gender: "All",
        benefits: "₹10,000 to ₹60,000 per year depending on the state and course of study.",
        deadline: "2026-07-31",
        required_documents: ["10th Marksheet", "Income Certificate", "Photograph"],
        official_website: "https://www.vidyadhan.org/",
        application_link: "https://www.vidyadhan.org/",
        minority_status: false,
        disability_status: false,
    },
    {
        name: "Reliance Foundation Undergraduate Scholarships",
        provider: "Reliance Foundation",
        description: "Aiming to support undergraduate students with a grant to pursue their higher education and empower them to unlock their potential.",
        eligibility_criteria: "Resident Indian pursuing first-year of full-time UG degree in any stream. Aptitude test required.",
        education_level: ["Undergraduate"],
        category: ["General", "OBC", "SC", "ST"],
        income_limit: 1500000,
        marks_requirement: 60,
        state: "All India",
        gender: "All",
        benefits: "Up to ₹2,000,000 over the duration of the degree. Includes alumni network access.",
        deadline: "2026-10-15",
        required_documents: ["12th Marksheet", "Income Proof", "Aptitude Test Score"],
        official_website: "https://scholarships.reliancefoundation.org/",
        application_link: "https://scholarships.reliancefoundation.org/",
        minority_status: false,
        disability_status: false,
    },
    {
        name: "HDFC Badhte Kadam Scholarship",
        provider: "HDFC Bank",
        description: "Aimed at helping students continue their education despite facing a recent life crisis or having a low family income.",
        eligibility_criteria: "Students from Class 11 to PG, inclusive of general, professional and vocational courses. Must have faced recent crisis.",
        education_level: ["12th", "Diploma", "Undergraduate", "Postgraduate"],
        category: ["General", "OBC", "SC", "ST"],
        income_limit: 600000,
        marks_requirement: 60,
        state: "All India",
        gender: "All",
        benefits: "Financial aid from ₹18,000 to ₹100,000 depending on the course of study.",
        deadline: "2026-09-30",
        required_documents: ["Marksheet", "Income Proof", "Proof of Crisis (Death cert/Job loss proof)"],
        official_website: "https://www.hdfcbank.com/",
        application_link: "https://www.hdfcbank.com/",
        minority_status: false,
        disability_status: false,
    },
    {
        name: "Keep India Smiling Foundational Scholarship Programme",
        provider: "Colgate-Palmolive (India) Limited",
        description: "Aims to provide foundational support to individuals who are deserving and meritorious but may lack resources.",
        eligibility_criteria: "Students enrolled in Class 11, Diploma, Graduation (Engineering/Vocational). Minimum 60% in board exams.",
        education_level: ["12th", "Diploma", "Undergraduate"],
        category: ["General", "OBC", "SC", "ST"],
        income_limit: 500000,
        marks_requirement: 60,
        state: "All India",
        gender: "All",
        benefits: "Scholarship up to ₹30,000 per year for up to 4 years.",
        deadline: "2026-03-31",
        required_documents: ["Previous Marksheet", "Income Certificate", "Admission Proof"],
        official_website: "https://www.colgate.com/en-in/",
        application_link: "https://www.colgate.com/en-in/",
        minority_status: false,
        disability_status: false,
    },
    {
        name: "Tata Scholarship for Cornell University",
        provider: "Tata Education and Development Trust",
        description: "Full financial support for exceptional Indian students to pursue undergraduate education at Cornell University.",
        eligibility_criteria: "Indian citizen applying to Cornell University undergraduate programs. Must demonstrate exceptional financial need.",
        education_level: ["Undergraduate"],
        category: ["General", "OBC", "SC", "ST"],
        income_limit: 800000,
        marks_requirement: 85,
        state: "All India",
        gender: "All",
        benefits: "Covers full demonstrated financial need including tuition, room, board, and personal expenses.",
        deadline: "2026-01-02",
        required_documents: ["12th Marksheet", "Income Documents", "Cornell Application", "Essays"],
        official_website: "https://www.cornelladmissions.org/",
        application_link: "https://www.cornelladmissions.org/",
        minority_status: false,
        disability_status: false,
    },
    {
        name: "Inspire Scholarship for Higher Education (SHE)",
        provider: "Department of Science and Technology",
        description: "To attract talented youth to study Basic and Natural Sciences.",
        eligibility_criteria: "Students who scored in top 1% in Class XII and pursue Natural/Basic Sciences at UG/PG level.",
        education_level: ["Undergraduate", "Postgraduate"],
        category: ["General", "OBC", "SC", "ST"],
        income_limit: 0,
        marks_requirement: 90,
        state: "All India",
        gender: "All",
        benefits: "₹80,000 per annum + summer attachment fee ₹20,000 per annum.",
        deadline: "2026-11-30",
        required_documents: ["Class XII Marksheet (showing top 1% ranking)", "Admission Proof", "Bank Details"],
        official_website: "https://online-inspire.gov.in/",
        application_link: "https://online-inspire.gov.in/",
        minority_status: false,
        disability_status: false,
    },
    {
        name: "Dr. APJ Abdul Kalam Ignite Awards",
        provider: "National Innovation Foundation (NIF)",
        description: "National competition of original technological ideas and innovations by children.",
        eligibility_criteria: "Students up to class 12 or out of school up to the age of 17 years. Based on original technological ideas/innovations.",
        education_level: ["10th", "12th"],
        category: ["General", "OBC", "SC", "ST"],
        income_limit: 0,
        marks_requirement: 0,
        state: "All India",
        gender: "All",
        benefits: "Financial support for prototyping, patenting, and recognition.",
        deadline: "2026-08-31",
        required_documents: ["Innovation Details", "Proof of Identity", "School ID"],
        official_website: "http://nif.org.in/ignite/",
        application_link: "http://nif.org.in/ignite/",
        minority_status: false,
        disability_status: false,
    },
    {
        name: "Kishore Vaigyanik Protsahan Yojana (KVPY)",
        provider: "Department of Science and Technology",
        description: "National Program of Fellowship in Basic Sciences to encourage students to take up research careers in Science.",
        eligibility_criteria: "Students enrolled in XI Standard, XII Standard, or 1st year of UG courses in Basic Sciences.",
        education_level: ["12th", "Undergraduate"],
        category: ["General", "OBC", "SC", "ST"],
        income_limit: 0,
        marks_requirement: 60,
        state: "All India",
        gender: "All",
        benefits: "Monthly fellowship of ₹5000 to ₹7000 + Annual contingency grant of ₹20000 to ₹28000.",
        deadline: "2026-09-06",
        required_documents: ["Marksheets", "Caste Certificate (if applicable)", "Passport Size Photo", "Signature"],
        official_website: "http://kvpy.iisc.ernet.in/",
        application_link: "http://kvpy.iisc.ernet.in/",
        minority_status: false,
        disability_status: false,
    },
    {
        name: "Prime Minister's Research Fellowship (PMRF)",
        provider: "Ministry of Education",
        description: "To attract the best talent to doctoral programs of IITs and IISc.",
        eligibility_criteria: "Students with B.Tech/M.Tech/BS/MS from IITs, IISc, NITs, IISERs with CGPA 8.0+.",
        education_level: ["PhD"],
        category: ["General", "OBC", "SC", "ST"],
        income_limit: 0,
        marks_requirement: 80,
        state: "All India",
        gender: "All",
        benefits: "Monthly stipend ₹70,000–₹80,000. Research grant ₹2,00,000/year.",
        deadline: "2026-12-31",
        required_documents: ["Qualifying Degree Certificate", "CGPA Transcript", "Research Proposal"],
        official_website: "https://www.pmrf.in/",
        application_link: "https://www.pmrf.in/",
        minority_status: false,
        disability_status: false,
    },
    {
        name: "National Overseas Scholarship for ST Students",
        provider: "Ministry of Tribal Affairs",
        description: "Financial assistance for ST students to pursue higher studies abroad.",
        eligibility_criteria: "ST students aspiring to pursue Masters, PhD, and Post-Doctoral research in foreign universities. Minimum 60% in Bachelor's degree.",
        education_level: ["Postgraduate", "PhD"],
        category: ["ST"],
        income_limit: 600000,
        marks_requirement: 60,
        state: "All India",
        gender: "All",
        benefits: "Tuition fees, maintenance allowance, air passage, health insurance (Approx USD 15,400+ per year).",
        deadline: "2026-03-31",
        required_documents: ["ST Certificate", "Passport", "Admission Letter from Foreign University", "Marksheet"],
        official_website: "https://scholarships.gov.in/",
        application_link: "https://scholarships.gov.in/",
        minority_status: false,
        disability_status: false,
    },
    {
        name: "Wipro Education Fellowship",
        provider: "Wipro Foundation",
        description: "Fellowship program for teachers who want to drive systemic change in Indian school education.",
        eligibility_criteria: "Graduates with 2+ years work experience in education sector. Passionate about school education reform.",
        education_level: ["Undergraduate", "Postgraduate"],
        category: ["General", "OBC", "SC", "ST"],
        income_limit: 0,
        marks_requirement: 0,
        state: "All India",
        gender: "All",
        benefits: "Monthly stipend, travel expenses, and mentorship from education leaders.",
        deadline: "2026-06-30",
        required_documents: ["Resume/CV", "Work Experience Certificate", "Degree Certificate", "Statement of Purpose"],
        official_website: "https://www.wipro.com/",
        application_link: "https://www.wipro.com/",
        minority_status: false,
        disability_status: false,
    },
    {
        name: "Azim Premji University Scholarship",
        provider: "Azim Premji Foundation",
        description: "Full and partial scholarships for students pursuing MA Education, MA Development, and other programs at Azim Premji University.",
        eligibility_criteria: "Indian citizens with an undergraduate degree. Committed to development and education sector work.",
        education_level: ["Postgraduate"],
        category: ["General", "OBC", "SC", "ST"],
        income_limit: 400000,
        marks_requirement: 50,
        state: "All India",
        gender: "All",
        benefits: "Full tuition fee waiver + living stipend for selected candidates.",
        deadline: "2026-04-30",
        required_documents: ["UG Degree Certificate", "Income Certificate", "Statement of Purpose", "Aadhaar"],
        official_website: "https://azimpremjiuniversity.edu.in/",
        application_link: "https://azimpremjiuniversity.edu.in/",
        minority_status: false,
        disability_status: false,
    },
];

export async function scrapePrivate(): Promise<ScraperResult> {
    const start = Date.now();
    const errors: string[] = [];
    const scholarships: ScrapedScholarship[] = [];

    try {
        logger.scraperStart(SOURCE);

        for (const raw of PRIVATE_SCHOLARSHIPS) {
            try {
                scholarships.push(normalizeScholarship(raw, SOURCE));
            } catch (err) {
                const msg = `Failed to normalize: ${raw.name}`;
                errors.push(msg);
                logger.error(SOURCE, msg, err);
            }
        }
    } catch (err) {
        errors.push("Private foundation scraper failure");
        logger.error(SOURCE, "Private foundation scraper failure", err);
    }

    const duration = Date.now() - start;
    logger.scraperEnd(SOURCE, scholarships.length, duration);
    return { source: SOURCE, scholarships, errors, duration_ms: duration };
}
