// State Scholarship Portal scrapers

import { ScrapedScholarship, ScraperResult } from "../types";
import { normalizeScholarship } from "../utils/normalizer";
import { logger } from "../utils/logger";

const SOURCE = "STATE_PORTALS";

const STATE_SCHOLARSHIPS: Partial<ScrapedScholarship>[] = [
    {
        name: "Mukhyamantri Medhavi Vidyarthi Yojana",
        provider: "Government of Madhya Pradesh",
        description: "To financially assist talented students from MP pursuing higher education in prestigious national institutes or state colleges.",
        eligibility_criteria: "MP domicile. Secured 70% or more (MP Board) or 85% or more (CBSE/ICSE) in 12th. Admitted to preferred UG courses.",
        education_level: ["Undergraduate"],
        category: ["General", "OBC", "SC", "ST"],
        income_limit: 600000,
        marks_requirement: 70,
        state: "Madhya Pradesh",
        gender: "All",
        benefits: "100% tuition fee waiver/reimbursement.",
        deadline: "2026-12-31",
        required_documents: ["MP Domicile Certificate", "12th Marksheet", "Income Certificate", "Aadhaar Card", "Admission Letter"],
        official_website: "http://scholarshipportal.mp.nic.in/",
        application_link: "http://scholarshipportal.mp.nic.in/",
        minority_status: false,
        disability_status: false,
    },
    {
        name: "MahaDBT Post Matric Scholarship",
        provider: "Government of Maharashtra",
        description: "Umbrella portal for all post-matric scholarships administered by Maharashtra government, including Rajarshi Chhatrapati Shahu Maharaj Shikshan Shulkh Shishyavrutti Yojna.",
        eligibility_criteria: "Maharashtra domicile. EBC, SC, ST, OBC, VJNT, SBC category students pursuing authorized courses.",
        education_level: ["12th", "Diploma", "Undergraduate", "Postgraduate", "PhD"],
        category: ["General", "EWS", "OBC", "SC", "ST"],
        income_limit: 800000,
        marks_requirement: 0,
        state: "Maharashtra",
        gender: "All",
        benefits: "Tuition fee reimbursement ranging from 50% to 100%. Exam fee reimbursement. Maintenance allowance.",
        deadline: "2026-12-31",
        required_documents: ["Maharashtra Domicile Certificate", "Income Certificate", "Caste Certificate (if applicable)", "Previous Year Marksheet", "Fee Receipt"],
        official_website: "https://mahadbt.maharashtra.gov.in/",
        application_link: "https://mahadbt.maharashtra.gov.in/",
        minority_status: false,
        disability_status: false,
    },
    {
        name: "Swami Vivekananda Merit Cum Means Scholarship",
        provider: "Government of West Bengal",
        description: "Assisting meritorious students of West Bengal belonging to economically backward families to pursue higher studies.",
        eligibility_criteria: "West Bengal domicile. Must pass out from WB board. Class 11/12 (60% marks). UG (60% marks in 12th). PG (53% marks in Graduation).",
        education_level: ["12th", "Undergraduate", "Postgraduate"],
        category: ["General", "OBC", "SC", "ST"],
        income_limit: 250000,
        marks_requirement: 60,
        state: "West Bengal",
        gender: "All",
        benefits: "₹1,000 to ₹5,000 per month depending on the level of course.",
        deadline: "2026-11-30",
        required_documents: ["WB Domicile", "Income Certificate", "Marksheet of Qualifying Exam", "Bank Passbook"],
        official_website: "https://svmcm.wbhed.gov.in/",
        application_link: "https://svmcm.wbhed.gov.in/",
        minority_status: false,
        disability_status: false,
    },
    {
        name: "Dr. YSR Vidyadheevena Scheme",
        provider: "Government of Andhra Pradesh",
        description: "Provides full fee reimbursement to students belonging to poor families giving them access to higher education.",
        eligibility_criteria: "AP domicile. Pursuing Polytechnic, ITI, Degree, PG/Ph.D courses. Available for SC, ST, BC, EBC, Minorities, Kapu, and Differently Abled students.",
        education_level: ["Diploma", "Undergraduate", "Postgraduate", "PhD"],
        category: ["General", "OBC", "SC", "ST", "EWS"],
        income_limit: 250000,
        marks_requirement: 0,
        state: "Andhra Pradesh",
        gender: "All",
        benefits: "Full Fee Reimbursement (Tuition fee, special fee, other fees). Credited directly to mother's account in 4 quarters.",
        deadline: "2026-12-31",
        required_documents: ["AP Domicile/Aadhaar", "Income Certificate/Ration Card", "Caste Certificate", "Admission details"],
        official_website: "https://jnanabhumi.ap.gov.in/",
        application_link: "https://jnanabhumi.ap.gov.in/",
        minority_status: false,
        disability_status: false,
    },
    {
        name: "Chief Minister's Scholarship Scheme for Higher Education",
        provider: "Delhi Government",
        description: "Assists meritorious students from moderate backgrounds in Delhi.",
        eligibility_criteria: "Student must be a resident of Delhi studying in a state university in Delhi.",
        education_level: ["Undergraduate", "Postgraduate"],
        category: ["General", "OBC", "SC", "ST"],
        income_limit: 600000,
        marks_requirement: 60,
        state: "Delhi",
        gender: "All",
        benefits: "Full fee waiver for income <₹2.5 Lakhs, 50% for ₹2.5-₹6 Lakhs.",
        deadline: "2026-12-31",
        required_documents: ["Delhi Domicile", "Income Certificate", "University Admission Proof"],
        official_website: "https://edistrict.delhigovt.nic.in/",
        application_link: "https://edistrict.delhigovt.nic.in/",
        minority_status: false,
        disability_status: false,
    },
    {
        name: "NSP Pre Matric Scholarship for SC Students, Karnataka",
        provider: "Government of Karnataka",
        description: "Financial assistance for SC students at secondary school level in Karnataka.",
        eligibility_criteria: "SC students from Karnataka studying in classes 9 to 10.",
        education_level: ["10th"],
        category: ["SC"],
        income_limit: 250000,
        marks_requirement: 0,
        state: "Karnataka",
        gender: "All",
        benefits: "Maintenance allowance, book grants, and reimbursement of non-refundable fees.",
        deadline: "2026-11-15",
        required_documents: ["Caste Certificate", "Income Certificate", "Karnataka Domicile", "Aadhaar", "Bank Account Details"],
        official_website: "https://ssp.postmatric.karnataka.gov.in/",
        application_link: "https://ssp.postmatric.karnataka.gov.in/",
        minority_status: false,
        disability_status: false,
    },
    {
        name: "NEC Merit Scholarship (North Eastern Council)",
        provider: "Ministry of Development of North Eastern Region (DoNER)",
        description: "Scholarships for students of North Eastern Region for pursuing higher professional courses.",
        eligibility_criteria: "Domicile of North Eastern States pursuing Diploma/Degree/PG courses. Minimum 60% in qualifying exam.",
        education_level: ["Diploma", "Undergraduate", "Postgraduate"],
        category: ["General", "OBC", "SC", "ST"],
        income_limit: 800000,
        marks_requirement: 60,
        state: "All India",
        gender: "All",
        benefits: "Diploma: ₹20,000/year, Degree: ₹22,000/year, PG: ₹25,000/year, PhD: ₹30,000/year.",
        deadline: "2026-12-31",
        required_documents: ["Domicile of NE State", "Marksheet", "Admission Proof", "Aadhaar"],
        official_website: "https://scholarships.gov.in/",
        application_link: "https://scholarships.gov.in/",
        minority_status: false,
        disability_status: false,
    },
    {
        name: "Telangana State Overseas Scholarship",
        provider: "Government of Telangana",
        description: "To enable meritorious students from backward communities to study at world-renowned foreign universities.",
        eligibility_criteria: "SC/ST/BC/EBC domicile students of Telangana aspiring to pursue PG in top-ranked foreign universities.",
        education_level: ["Postgraduate", "PhD"],
        category: ["SC", "ST", "OBC", "EWS"],
        income_limit: 500000,
        marks_requirement: 60,
        state: "Telangana",
        gender: "All",
        benefits: "Tuition fee up to $15,000/year. Living allowance USD 15,000/year. Airfare. Health insurance.",
        deadline: "2026-09-30",
        required_documents: ["Domicile Certificate", "Caste Certificate", "GRE/GMAT Score", "Admission Letter from Foreign University"],
        official_website: "https://telanganasociety.gov.in/",
        application_link: "https://telanganasociety.gov.in/",
        minority_status: false,
        disability_status: false,
    },
    {
        name: "Tamil Nadu Chief Minister's Higher Education Scholarship",
        provider: "Government of Tamil Nadu",
        description: "Financial aid for first-generation graduates from Tamil Nadu pursuing UG courses.",
        eligibility_criteria: "Tamil Nadu domicile. Family income below ₹2.5 lakh. First graduate in the family. Minimum 60% in 12th.",
        education_level: ["Undergraduate"],
        category: ["General", "OBC", "SC", "ST"],
        income_limit: 250000,
        marks_requirement: 60,
        state: "Tamil Nadu",
        gender: "All",
        benefits: "₹1,000 per month for 10 months per year, up to 4 years.",
        deadline: "2026-12-31",
        required_documents: ["Tamil Nadu Domicile", "Income Certificate", "12th Marksheet", "First Graduate Certificate", "Bank Details"],
        official_website: "https://www.tn.gov.in/",
        application_link: "https://scholarships.gov.in/",
        minority_status: false,
        disability_status: false,
    },
    {
        name: "E-Kalyan Bihar State Scholarship",
        provider: "Government of Bihar",
        description: "Post-matric scholarship for backward class, SC/ST students of Bihar.",
        eligibility_criteria: "Bihar domicile. SC/ST/OBC/EBC students. Studying in post-matric level courses.",
        education_level: ["12th", "Diploma", "Undergraduate", "Postgraduate"],
        category: ["OBC", "SC", "ST", "EWS"],
        income_limit: 250000,
        marks_requirement: 0,
        state: "Bihar",
        gender: "All",
        benefits: "Tuition fee reimbursement and maintenance allowance varying by course.",
        deadline: "2026-12-31",
        required_documents: ["Bihar Domicile", "Caste Certificate", "Income Certificate", "Previous Marksheet", "Aadhaar Card"],
        official_website: "https://ekalyan.bih.nic.in/",
        application_link: "https://ekalyan.bih.nic.in/",
        minority_status: false,
        disability_status: false,
    },
    {
        name: "Oasis Scholarship, West Bengal Minority",
        provider: "Government of West Bengal",
        description: "Scholarship for minority students of West Bengal at pre-matric and post-matric levels.",
        eligibility_criteria: "West Bengal domicile. Students from minority communities. Studying at all levels.",
        education_level: ["10th", "12th", "Undergraduate", "Postgraduate"],
        category: ["General", "OBC"],
        income_limit: 200000,
        marks_requirement: 50,
        state: "West Bengal",
        gender: "All",
        benefits: "Admission fee and maintenance allowance varying by course level.",
        deadline: "2026-12-31",
        required_documents: ["WB Domicile", "Minority Certificate", "Income Certificate", "Marksheet"],
        official_website: "https://wbmdfcscholarship.in/",
        application_link: "https://wbmdfcscholarship.in/",
        minority_status: true,
        disability_status: false,
    },
    {
        name: "Uttar Pradesh Post-Matric Scholarship",
        provider: "Government of Uttar Pradesh",
        description: "Financial assistance for SC/ST/OBC students of Uttar Pradesh pursuing post-matric education.",
        eligibility_criteria: "UP domicile. SC/ST/OBC students studying at post-matric level.",
        education_level: ["12th", "Diploma", "Undergraduate", "Postgraduate", "PhD"],
        category: ["OBC", "SC", "ST"],
        income_limit: 250000,
        marks_requirement: 0,
        state: "Uttar Pradesh",
        gender: "All",
        benefits: "Tuition fee reimbursement, maintenance allowance, and book grants.",
        deadline: "2026-12-31",
        required_documents: ["UP Domicile", "Caste Certificate", "Income Certificate", "Fee Receipt", "Aadhaar"],
        official_website: "https://scholarship.up.gov.in/",
        application_link: "https://scholarship.up.gov.in/",
        minority_status: false,
        disability_status: false,
    },
    {
        name: "Rajasthan Ambedkar DBT Voucher Yojana",
        provider: "Government of Rajasthan",
        description: "Residential/transport voucher for SC/ST/OBC/Minority/EWS students from Rajasthan studying away from home.",
        eligibility_criteria: "Rajasthan domicile. SC/ST/OBC/Minority/EWS students pursuing UG/PG in government institutions away from home district.",
        education_level: ["Undergraduate", "Postgraduate"],
        category: ["OBC", "SC", "ST", "EWS"],
        income_limit: 250000,
        marks_requirement: 0,
        state: "Rajasthan",
        gender: "All",
        benefits: "₹5,000–₹7,000 per month for 10 months (residential voucher). ₹10,000 per year (transport voucher).",
        deadline: "2026-12-31",
        required_documents: ["Rajasthan Domicile", "Caste Certificate", "Income Certificate", "College Admission Proof"],
        official_website: "https://sje.rajasthan.gov.in/",
        application_link: "https://sso.rajasthan.gov.in/",
        minority_status: false,
        disability_status: false,
    },
    {
        name: "Kerala State Merit Scholarship",
        provider: "Government of Kerala",
        description: "Merit scholarship for top-performing students in Kerala board examinations.",
        eligibility_criteria: "Kerala domicile. Scored in top ranks in SSLC or Plus Two examinations from Kerala Board.",
        education_level: ["12th", "Undergraduate"],
        category: ["General", "OBC", "SC", "ST"],
        income_limit: 0,
        marks_requirement: 80,
        state: "Kerala",
        gender: "All",
        benefits: "₹1,250 per month for SSLC toppers. ₹1,500 per month for Plus Two toppers.",
        deadline: "2026-10-31",
        required_documents: ["Kerala Domicile", "Board Exam Marksheet", "Bank Details", "Aadhaar"],
        official_website: "https://dcescholarship.kerala.gov.in/",
        application_link: "https://dcescholarship.kerala.gov.in/",
        minority_status: false,
        disability_status: false,
    },
    {
        name: "Punjab Merit Cum Means Scholarship",
        provider: "Government of Punjab",
        description: "Post-matric scholarship for meritorious students from economically weaker families in Punjab.",
        eligibility_criteria: "Punjab domicile. Minimum 60% marks. Pursuing post-matric courses.",
        education_level: ["12th", "Undergraduate", "Postgraduate"],
        category: ["General", "OBC", "SC", "ST"],
        income_limit: 400000,
        marks_requirement: 60,
        state: "Punjab",
        gender: "All",
        benefits: "Tuition fee reimbursement up to ₹30,000/year and maintenance allowance.",
        deadline: "2026-12-31",
        required_documents: ["Punjab Domicile", "Income Certificate", "Marksheet", "Fee Receipt"],
        official_website: "https://scholarships.gov.in/",
        application_link: "https://scholarships.gov.in/",
        minority_status: false,
        disability_status: false,
    },
    {
        name: "Gujarat State Scholarship for SC/ST Students",
        provider: "Government of Gujarat",
        description: "Post-matric scholarship for SC/ST students of Gujarat.",
        eligibility_criteria: "Gujarat domicile. SC/ST students pursuing post-matric courses.",
        education_level: ["12th", "Diploma", "Undergraduate", "Postgraduate"],
        category: ["SC", "ST"],
        income_limit: 250000,
        marks_requirement: 0,
        state: "Gujarat",
        gender: "All",
        benefits: "Full fee reimbursement plus maintenance allowance up to ₹1,200/month.",
        deadline: "2026-12-31",
        required_documents: ["Gujarat Domicile", "Caste Certificate", "Income Certificate", "Fee Receipt"],
        official_website: "https://digitalgujarat.gov.in/",
        application_link: "https://digitalgujarat.gov.in/",
        minority_status: false,
        disability_status: false,
    },
];

export async function scrapeStates(): Promise<ScraperResult> {
    const start = Date.now();
    const errors: string[] = [];
    const scholarships: ScrapedScholarship[] = [];

    try {
        logger.scraperStart(SOURCE);

        for (const raw of STATE_SCHOLARSHIPS) {
            try {
                scholarships.push(normalizeScholarship(raw, SOURCE));
            } catch (err) {
                const msg = `Failed to normalize: ${raw.name}`;
                errors.push(msg);
                logger.error(SOURCE, msg, err);
            }
        }
    } catch (err) {
        errors.push("State portals scraper failure");
        logger.error(SOURCE, "State portals scraper failure", err);
    }

    const duration = Date.now() - start;
    logger.scraperEnd(SOURCE, scholarships.length, duration);
    return { source: SOURCE, scholarships, errors, duration_ms: duration };
}
